package org.Exception;

public class Test {
public static void main(String[] args) {
	try {
		int a=10/0;
		System.out.println(a);
	}
	catch (Exception e) {
System.out.println("Something went wrong");
	}
	finally {
		System.out.println("Done....");
		
		System.out.println("Novfeel Task");
		System.out.println("sanjesh task");

<<<<<<< HEAD
=======
>>>>>>> 94620dadb0c64003b4c7f5d3a388b9ad3707dd4d
	}
}
}
